#!/bin/sh

# Fail early if any of the commands below fail.
set -e

case "$1" in
  configure)

    # Create a 'git' user if it does not exist with
    # the same parameters as below.
    adduser --system git

    if [ ! -f /etc/hoff.json ]; then
        # TODO: Put in a default?
        echo "You should now create /etc/hoff.json."
    fi

  ;;

esac

exit 0
