#!/bin/sh

# Fail early if any of the commands below fail.
set -e

case "$1" in
  configure)

    # Create a 'git' user if it does not exist with
    # the same parameters as below.
    adduser --system git

    # If the config file has not been modified (when the checksum matches that
    # of the example), tell the user to do so.
    # TODO: Update that hash, and automate computing it.
    if sha256sum /etc/hoff.json | grep -q "^8e38e15f2eadc4c6f09669d0ba40a"; then
        echo "You should now edit /etc/hoff.json."
    fi

  ;;

esac

exit 0
