# This Vagrant box is intended for building final artifacts in an environment
# similar to the production environment (Ubuntu 16.04 in this case). This is to
# keep dependencies on dynamic libraries consistent. For local development, just
# using Stack should be fine.

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.synced_folder "..", "/vagrant", type: "rsync"
  config.vm.provision "shell", inline: <<-SHELL
    # Retrieve the key used to sign the Stack package, add a repository for
    # Stack and install it. Also install an older version of GHC that --
    # although not used -- ensures that the dependencies are present already.
    sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 575159689BEFB442
    echo 'deb http://download.fpcomplete.com/ubuntu xenial main' | sudo tee /etc/apt/sources.list.d/fpco.list
    sudo apt update
    sudo apt install -y ghc stack
  SHELL

  # Give it a bit more headroom when doing the build.
  config.vm.provider "virtualbox" do |v|
    v.memory = 3096
  end
end
